using System;

namespace ClassifiedAds.Domain.Entities;

/// <summary>
/// Order entity representing a customer order.
/// Uses a composite business key (UserId + ExternalOrderRef) to prevent duplicate orders.
/// </summary>
public class Order : Entity<Guid>, IAggregateRoot
{
    /// <summary>
    /// The user who placed the order.
    /// Part of the unique business key (UserId, ExternalOrderRef).
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// External order reference from the client system (e.g., shopping cart ID, quote number).
    /// Part of the unique business key (UserId, ExternalOrderRef).
    /// </summary>
    public string ExternalOrderRef { get; set; }

    /// <summary>
    /// Order number generated by the system.
    /// </summary>
    public string OrderNumber { get; set; }

    /// <summary>
    /// Total amount of the order.
    /// </summary>
    public decimal TotalAmount { get; set; }

    /// <summary>
    /// Currency code (e.g., USD, EUR).
    /// </summary>
    public string Currency { get; set; }

    /// <summary>
    /// Order status (e.g., Pending, Confirmed, Shipped, Cancelled).
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// Optional notes or comments about the order.
    /// </summary>
    public string Notes { get; set; }

    // Navigation property to User
    public User User { get; set; }
}
